/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ViewingsRouteImport } from './routes/viewings'
import { Route as HomesIndexRouteImport } from './routes/homes.index'
import { Route as HomesIdRouteImport } from './routes/homes.$id'
import { Route as ListingsIndexRouteImport } from './routes/listings.index'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as PropertiesNewRouteImport } from './routes/properties.new'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiPublicV1HealthRouteImport } from './routes/api/public/v1/health'
import { Route as ApiV1HealthDatabaseRouteImport } from './routes/api/v1/health.database'
import { Route as PropertiesPropertyIdUnitsUnitIdRouteImport } from './routes/properties.$propertyId.units.$unitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewingsRoute = ViewingsRouteImport.update({
  id: '/viewings',
  path: '/viewings',
  getParentRoute: () => rootRouteImport,
} as any)
const HomesIndexRoute = HomesIndexRouteImport.update({
  id: '/homes/',
  path: '/homes/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomesIdRoute = HomesIdRouteImport.update({
  id: '/homes/$id',
  path: '/homes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesNewRoute = PropertiesNewRouteImport.update({
  id: '/properties/new',
  path: '/properties/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1HealthRoute = ApiPublicV1HealthRouteImport.update({
  id: '/api/public/v1/health',
  path: '/api/public/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthDatabaseRoute = ApiV1HealthDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => ApiV1HealthRoute,
} as any)
const PropertiesPropertyIdUnitsUnitIdRoute =
  PropertiesPropertyIdUnitsUnitIdRouteImport.update({
    id: '/properties/$propertyId/units/$unitId',
    path: '/properties/$propertyId/units/$unitId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/viewings': typeof ViewingsRoute
  '/homes/$id': typeof HomesIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/new': typeof PropertiesNewRoute
  '/homes/': typeof HomesIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/api/v1/health': typeof ApiV1HealthRouteWithChildren
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/v1/health/database': typeof ApiV1HealthDatabaseRoute
  '/properties/$propertyId/units/$unitId': typeof PropertiesPropertyIdUnitsUnitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/viewings': typeof ViewingsRoute
  '/homes/$id': typeof HomesIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/new': typeof PropertiesNewRoute
  '/homes': typeof HomesIndexRoute
  '/listings': typeof ListingsIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/api/v1/health': typeof ApiV1HealthRouteWithChildren
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/v1/health/database': typeof ApiV1HealthDatabaseRoute
  '/properties/$propertyId/units/$unitId': typeof PropertiesPropertyIdUnitsUnitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/viewings': typeof ViewingsRoute
  '/homes/$id': typeof HomesIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/new': typeof PropertiesNewRoute
  '/homes/': typeof HomesIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/api/v1/health': typeof ApiV1HealthRouteWithChildren
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/v1/health/database': typeof ApiV1HealthDatabaseRoute
  '/properties/$propertyId/units/$unitId': typeof PropertiesPropertyIdUnitsUnitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/applications'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/messages'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/saved'
    | '/settings'
    | '/verify-email'
    | '/viewings'
    | '/homes/$id'
    | '/listings/$id'
    | '/properties/$id'
    | '/properties/new'
    | '/homes/'
    | '/listings/'
    | '/properties/'
    | '/api/v1/health'
    | '/api/public/v1/health'
    | '/api/v1/health/database'
    | '/properties/$propertyId/units/$unitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/applications'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/messages'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/saved'
    | '/settings'
    | '/verify-email'
    | '/viewings'
    | '/homes/$id'
    | '/listings/$id'
    | '/properties/$id'
    | '/properties/new'
    | '/homes'
    | '/listings'
    | '/properties'
    | '/api/v1/health'
    | '/api/public/v1/health'
    | '/api/v1/health/database'
    | '/properties/$propertyId/units/$unitId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/applications'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/messages'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/saved'
    | '/settings'
    | '/verify-email'
    | '/viewings'
    | '/homes/$id'
    | '/listings/$id'
    | '/properties/$id'
    | '/properties/new'
    | '/homes/'
    | '/listings/'
    | '/properties/'
    | '/api/v1/health'
    | '/api/public/v1/health'
    | '/api/v1/health/database'
    | '/properties/$propertyId/units/$unitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplicationsRoute: typeof ApplicationsRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ViewingsRoute: typeof ViewingsRoute
  HomesIdRoute: typeof HomesIdRoute
  ListingsIdRoute: typeof ListingsIdRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  PropertiesNewRoute: typeof PropertiesNewRoute
  HomesIndexRoute: typeof HomesIndexRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  ApiV1HealthRoute: typeof ApiV1HealthRouteWithChildren
  ApiPublicV1HealthRoute: typeof ApiPublicV1HealthRoute
  PropertiesPropertyIdUnitsUnitIdRoute: typeof PropertiesPropertyIdUnitsUnitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewings': {
      id: '/viewings'
      path: '/viewings'
      fullPath: '/viewings'
      preLoaderRoute: typeof ViewingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homes/': {
      id: '/homes/'
      path: '/homes'
      fullPath: '/homes/'
      preLoaderRoute: typeof HomesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homes/$id': {
      id: '/homes/$id'
      path: '/homes/$id'
      fullPath: '/homes/$id'
      preLoaderRoute: typeof HomesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/new': {
      id: '/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof PropertiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/health': {
      id: '/api/public/v1/health'
      path: '/api/public/v1/health'
      fullPath: '/api/public/v1/health'
      preLoaderRoute: typeof ApiPublicV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health/database': {
      id: '/api/v1/health/database'
      path: '/database'
      fullPath: '/api/v1/health/database'
      preLoaderRoute: typeof ApiV1HealthDatabaseRouteImport
      parentRoute: typeof ApiV1HealthRoute
    }
    '/properties/$propertyId/units/$unitId': {
      id: '/properties/$propertyId/units/$unitId'
      path: '/properties/$propertyId/units/$unitId'
      fullPath: '/properties/$propertyId/units/$unitId'
      preLoaderRoute: typeof PropertiesPropertyIdUnitsUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiV1HealthRouteChildren {
  ApiV1HealthDatabaseRoute: typeof ApiV1HealthDatabaseRoute
}

const ApiV1HealthRouteChildren: ApiV1HealthRouteChildren = {
  ApiV1HealthDatabaseRoute: ApiV1HealthDatabaseRoute,
}

const ApiV1HealthRouteWithChildren = ApiV1HealthRoute._addFileChildren(
  ApiV1HealthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplicationsRoute: ApplicationsRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ViewingsRoute: ViewingsRoute,
  HomesIdRoute: HomesIdRoute,
  ListingsIdRoute: ListingsIdRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  PropertiesNewRoute: PropertiesNewRoute,
  HomesIndexRoute: HomesIndexRoute,
  ListingsIndexRoute: ListingsIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  ApiV1HealthRoute: ApiV1HealthRouteWithChildren,
  ApiPublicV1HealthRoute: ApiPublicV1HealthRoute,
  PropertiesPropertyIdUnitsUnitIdRoute: PropertiesPropertyIdUnitsUnitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
